# Generated by Django 4.2.11 on 2024-03-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(related_name='bookings', to='room.room'),
        ),
    ]
